#!/bin/sh

# *************************************************
#
# A shell script for preparing bare repos that autodeploy.
#
# @package    Build
# @author     Scott Travis <scott.w.travis@gmail.com>
# @link       http://github.com/swt83/git-deploy
# @license    MIT License
#
# *************************************************

# -------------------------------------------------
# CAPTURE PROJECT NAME
# -------------------------------------------------
WORKTREE="$1"
if [ "$WORKTREE" = "" ]
then
	echo "You failed to provide a build name!"
	exit 1
fi

# -------------------------------------------------
# CREATE DEPLOYMENT DIRECTORY
# -------------------------------------------------
mkdir /var/www/html/$WORKTREE

# -------------------------------------------------
# CREATE BARE REPOSITORY
# -------------------------------------------------
mkdir $WORKTREE
cd $WORKTREE
git init --bare
git config core.worktree /var/www/html/$WORKTREE
git config core.bare false
git config receive.denycurrentbranch ignore

# -------------------------------------------------
# CREATE POST-RECEIVE HOOK
# -------------------------------------------------
cd hooks
echo -e "#!/bin/sh\ngit checkout -f" > post-receive
chmod +x post-receive
cd ~
