#!/bin/sh

# *************************************************
#
# A shell script for securing IPTables automatically.
#
# @package    IPTables
# @author     Scott Travis <scott.w.travis@gmail.com>
# @link       http://github.com/swt83/git-deploy
# @license    MIT License
#
# *************************************************

# -------------------------------------------------
# FLUSH TABLE
# -------------------------------------------------
echo ""
sudo iptables -F

# -------------------------------------------------
# OPEN SPECIFIC PORTS
# -------------------------------------------------
sudo iptables -I INPUT -p tcp --dport 22 -j ACCEPT
sudo iptables -I INPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -I INPUT -p tcp --dport 443 -j ACCEPT

# -------------------------------------------------
# OPEN SPECIFIC PORTS FOR SPECIFIC IPs
# -------------------------------------------------
if [ "$1" = "open" ] && [ "$2" != "" ] && [ "$3" != "" ]
then
	sudo iptables -A INPUT -p tcp -s $3 --dport $2 -j ACCEPT
fi

# -------------------------------------------------
# BLOCK SPECIFIC IPs
# -------------------------------------------------
if [ "$1" = "block" ] && [ "$2" != "" ]
then
	sudo iptables -A INPUT -s $2 -j DROP
fi

# -------------------------------------------------
# FINALIZE CHAIN
# -------------------------------------------------
sudo iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
sudo iptables -A INPUT -j REJECT

# -------------------------------------------------
# SET DROP POLICIES
# -------------------------------------------------
sudo iptables -P INPUT DROP
# sudo iptables -P FORWARD DROP
# sudo iptables -P OUTPUT DROP

# -------------------------------------------------
# SAVE & RESTART
# -------------------------------------------------
sudo service iptables save
sudo service iptables restart

# -------------------------------------------------
# SHOW CHANGES
# -------------------------------------------------
echo ""
echo "\033[1;31m""/////////////////////////////////////////////////""\033[0m";
sudo iptables -L
echo "\033[1;31m""/////////////////////////////////////////////////""\033[0m";
echo ""